### PR TITLE
Add .loadIntegrations() method to builder

### PR DESCRIPTION
**Pull request by lhotari**
- makes it easier to customize BlockHound

### CODE REVIEW

**Comment by bsideup** [comment]
Hi @lhotari,

Could you please provide an example how the new API makes it easier compared to [the existing ones](https://github.com/reactor/BlockHound/blob/master/docs/customization.md#customization)

Thank you!

**Comment by lhotari** [comment]
> Could you please provide an example how the new API makes it easier compared to [the existing ones](https://github.com/reactor/BlockHound/blob/master/docs/customization.md#customization)

I'm sorry I didn't properly explain the context at first.

My use case is such that I'd like to use the builder and also get the integrations loaded. I believe that this would be useful in most cases when customizing the behavior of BlockHound.

I had the problem that some tests were hanging after enabling BlockHound for all tests. I followed the tip in https://github.com/reactor/BlockHound/blob/master/docs/tips.md#debugging to add a `blockingMethodCallback`:

```
    static {
        BlockHound.Builder builder = BlockHound.builder()
                .blockingMethodCallback(method -> {
                    Error error = new BlockingOperationError(method);
                    // Print out the blocking call to find out problem when exceptions are swallowed
                    error.printStackTrace(System.err);
                    throw error;
                });
        ServiceLoader<BlockHoundIntegration> serviceLoader = ServiceLoader.load(BlockHoundIntegration.class);
        StreamSupport.stream(serviceLoader.spliterator(), false).sorted().forEach(builder::with);
        builder.install();
    }
```

I had to look into the source code of BlockHound to find out how to get the integrations loaded with the ServiceLoader. After adding the `.loadIntegrations` to the builder, this type of use case would become simpler:
```
    static {
        BlockHound.builder()
                .blockingMethodCallback(method -> {
                    Error error = new BlockingOperationError(method);
                    // Print out the blocking call to find out problem when exceptions are swallowed
                    error.printStackTrace(System.err);
                    throw error;
                })
                .loadIntegrations()
                .install();
    }
```

**Comment by bsideup** [comment]
@lhotari 
No problem, thanks for providing a rich context!

> My use case is such that I'd like to use the builder and also get the integrations loaded.

This sounds like the option number 2:
> 2. `BlockHound.install(BlockHoundIntegration... integrations)` - same as `BlockHound.install()`, but adds user-provided integrations to the list.

So that you can do:
```java
BlockHound.install(b -> {
    b. blockingMethodCallback(...);
});
```

WDYT about adding it to the tips instead? :)

**Comment by lhotari** [comment]
> ```java
> BlockHound.install(b -> {
>     b. blockingMethodCallback(...);
> });
> ```
Thanks, now I got it. I missed that the API could be used that way.
I'll close the PR since it's not needed. 
 
> WDYT about adding it to the tips instead? :)
Good idea. I'll do that instead.

**Comment by lhotari** [comment]
I created #81 to improve the example in tips.

**Pull request closed without merging**
